# Generated by Django 3.0.5 on 2020-07-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200712_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(height_field=300, upload_to='portfolio/images', width_field=400),
        ),
    ]
